import { API_BASE_URL, API_ENDPOINTS, apiFetch } from './config';

// --- Per-terminal OSM ID → Tank ID mappings ---
// Maps 3D scene mesh names (OSM building IDs) to tank database IDs.
// Generated by scanning GLB files for cylindrical meshes, sorted by size.

const SAVANNAH_TANKS: Record<string, string> = {
  '963060345': 'TK-301', '295318118': 'TK-302', '295318124': 'TK-201', '295318123': 'TK-202',
  '295318125': 'TK-203', '295318127': 'TK-101', '295318128': 'TK-102', '295318129': 'TK-103',
  '295318117': 'TK-401', '295318119': 'TK-402', '295318120': 'TK-503', '295318121': 'TK-501',
  '295318122': 'TK-504', '295318126': 'TK-502', '295318477': 'TK-511', '295318478': 'TK-519',
  '295318479': 'TK-505', '295318480': 'TK-520', '295318481': 'TK-521', '295318482': 'TK-522',
  '295318483': 'TK-523', '295318484': 'TK-512', '963018304': 'TK-526', '963018305': 'TK-527',
  '963018306': 'TK-528', '963018307': 'TK-529', '963018308': 'TK-530', '963018309': 'TK-531',
  '963018310': 'TK-532', '963018311': 'TK-533', '963018312': 'TK-534', '963018313': 'TK-506',
  '963018314': 'TK-507', '963018315': 'TK-508', '963018316': 'TK-509', '963060349': 'TK-524',
  '963060350': 'TK-525', '963060351': 'TK-536', '963060352': 'TK-537', '963060353': 'TK-538',
  '963060354': 'TK-539', '963060355': 'TK-540', '963060356': 'TK-541', '963060357': 'TK-542',
  '963060358': 'TK-543', '963060359': 'TK-544', '963060360': 'TK-545', '963060361': 'TK-546',
  '963060362': 'TK-547', '963060363': 'TK-548', '963060364': 'TK-513', '963060365': 'TK-514',
  '963060366': 'TK-515', '963060367': 'TK-516', '963060368': 'TK-517', '963060369': 'TK-510',
  '1286707729': 'TK-518', '1286707730': 'TK-535', '1286707731': 'TK-549',
};

const LA_TANKS: Record<string, string> = {
  '408511420': 'TK-101', '408511662': 'TK-102', '408511679': 'TK-103', '408511682': 'TK-104',
  '408511733': 'TK-105', '408511802': 'TK-106', '408511810': 'TK-107', '408511828': 'TK-108',
  '408511867': 'TK-109', '408511872': 'TK-110', '408511874': 'TK-201', '408511900': 'TK-202',
  '408511907': 'TK-203', '408511930': 'TK-204', '408511964': 'TK-205', '408511972': 'TK-206',
  '408512036': 'TK-207', '408512044': 'TK-208', '408512062': 'TK-209', '408512111': 'TK-210',
  '408512134': 'TK-301', '408512150': 'TK-302', '408512151': 'TK-303', '408512152': 'TK-304',
  '408512153': 'TK-305', '408512155': 'TK-306', '408512157': 'TK-307', '408512161': 'TK-308',
  '408512168': 'TK-309', '408512170': 'TK-310', '408512172': 'TK-401', '408512181': 'TK-402',
  '408512186': 'TK-403', '408512196': 'TK-404', '408512200': 'TK-405', '408512203': 'TK-406',
  '408512204': 'TK-407', '408512208': 'TK-408', '408512216': 'TK-409', '408512219': 'TK-410',
  '408512228': 'TK-501', '408512230': 'TK-502', '408512232': 'TK-503', '408512238': 'TK-504',
  '408512240': 'TK-505', '408512242': 'TK-506', '408512245': 'TK-507', '408512254': 'TK-508',
  '408512258': 'TK-509', '408512268': 'TK-510', '408512269': 'TK-601', '408512275': 'TK-602',
  '408512279': 'TK-603', '408512286': 'TK-604', '408512287': 'TK-605', '408512292': 'TK-606',
  '408512295': 'TK-607', '408512300': 'TK-608', '408512309': 'TK-609', '408512316': 'TK-610',
  '408512324': 'TK-701', '408512327': 'TK-702', '408512330': 'TK-703', '408512337': 'TK-704',
};

const TARRAGONA_TANKS: Record<string, string> = {
  '99699572': 'TK-101', '99699575': 'TK-102', '99699577': 'TK-103', '99699579': 'TK-104',
  '99699581': 'TK-105', '99699584': 'TK-106', '99699586': 'TK-107', '99699588': 'TK-108',
  '99699591': 'TK-109', '99699593': 'TK-110', '99699595': 'TK-201', '99699597': 'TK-202',
  '99699599': 'TK-203', '99699602': 'TK-204', '99699604': 'TK-205', '99699606': 'TK-206',
  '99699608': 'TK-207', '99699610': 'TK-208', '99699612': 'TK-209', '99699615': 'TK-210',
  '99699616': 'TK-301', '99699618': 'TK-302', '99699621': 'TK-303', '99699623': 'TK-304',
  '99699626': 'TK-305', '99699628': 'TK-306', '99699631': 'TK-307', '99699632': 'TK-308',
  '99699635': 'TK-309', '99699638': 'TK-310', '99699640': 'TK-401', '99699642': 'TK-402',
  '99699645': 'TK-403', '99699647': 'TK-404', '99699649': 'TK-405', '99699651': 'TK-406',
  '99699653': 'TK-407', '99699656': 'TK-408', '99699659': 'TK-409', '99699660': 'TK-410',
  '99699663': 'TK-501', '99699666': 'TK-502', '99699669': 'TK-503', '99699670': 'TK-504',
  '99699674': 'TK-505', '99699675': 'TK-506', '99699678': 'TK-507', '99699681': 'TK-508',
  '99699683': 'TK-509', '99699686': 'TK-510', '99699688': 'TK-601', '99699691': 'TK-602',
  '99699693': 'TK-603', '99699696': 'TK-604', '99699699': 'TK-605', '99699700': 'TK-606',
  '99699703': 'TK-607', '99699704': 'TK-608', '99699706': 'TK-609', '99699708': 'TK-610',
  '99699710': 'TK-701', '99699712': 'TK-702', '99699715': 'TK-703', '99699716': 'TK-704',
  '99699719': 'TK-705', '99699721': 'TK-706', '99699723': 'TK-707', '99699726': 'TK-708',
  '99699728': 'TK-709', '99699731': 'TK-710', '99699733': 'TK-801', '99699735': 'TK-802',
  '99699737': 'TK-803', '99699739': 'TK-804', '99699741': 'TK-805', '99699743': 'TK-806',
  '99699745': 'TK-807', '99699748': 'TK-808', '99699750': 'TK-809', '99699752': 'TK-810',
  '99699754': 'TK-901', '99699758': 'TK-902', '99699760': 'TK-903', '99699761': 'TK-904',
  '99699764': 'TK-905', '99699767': 'TK-906', '99699770': 'TK-907', '99699771': 'TK-908',
  '99699774': 'TK-909', '99699776': 'TK-910', '99699779': 'TK-1001', '99699781': 'TK-1002',
  '99699783': 'TK-1003', '99699785': 'TK-1004', '99699788': 'TK-1005', '99699789': 'TK-1006',
  '99699792': 'TK-1007', '99699795': 'TK-1008', '99699798': 'TK-1009', '99699799': 'TK-1010',
  '99699802': 'TK-1101', '99699804': 'TK-1102', '99699807': 'TK-1103', '99699809': 'TK-1104',
  '99699811': 'TK-1105', '99699814': 'TK-1106', '99699816': 'TK-1107', '99699819': 'TK-1108',
  '99699821': 'TK-1109', '99699822': 'TK-1110', '99699824': 'TK-1201', '99699827': 'TK-1202',
  '99699829': 'TK-1203', '99699832': 'TK-1204', '99699835': 'TK-1205',
};

// Per-terminal mapping lookup
const TERMINAL_TANK_MAPS: Record<string, Record<string, string>> = {
  'savannah': SAVANNAH_TANKS,
  'los-angeles': LA_TANKS,
  'tarragona': TARRAGONA_TANKS,
};

function getActiveMap(): Record<string, string> {
  if (typeof window !== 'undefined') {
    const tid = localStorage.getItem('vopak_active_terminal') || 'savannah';
    return TERMINAL_TANK_MAPS[tid] ?? SAVANNAH_TANKS;
  }
  return SAVANNAH_TANKS;
}

export function osmToTankId(osmId: string): string | null {
  return getActiveMap()[osmId] ?? null;
}

export function isMappedTank(osmId: string): boolean {
  return osmId in getActiveMap();
}

// --- Tank data types ---

export type TankStatus =
  | 'in_service'
  | 'receiving'
  | 'discharging'
  | 'idle'
  | 'heating'
  | 'warning'
  | 'critical'
  | 'maintenance';

export interface TankLevelData {
  id: number;
  tank: string;
  product: string;
  level: number;
  volume: number;
  capacity: number;
  color: string;
  status: TankStatus;
}

// Status display config for UI and 3D visualization
export const TANK_STATUS_CONFIG: Record<TankStatus, { label: string; color: string; icon: string }> = {
  in_service:  { label: 'In Service',  color: '#5CE5A0', icon: 'check-circle' },
  receiving:   { label: 'Receiving',   color: '#56CDE7', icon: 'arrow-down' },
  discharging: { label: 'Discharging', color: '#4D65FF', icon: 'arrow-up' },
  idle:        { label: 'Idle',        color: '#94A3B8', icon: 'pause-circle' },
  heating:     { label: 'Heating',     color: '#F6AD55', icon: 'flame' },
  warning:     { label: 'Warning',     color: '#ECC94B', icon: 'alert-triangle' },
  critical:    { label: 'Critical',    color: '#E53E3E', icon: 'alert-octagon' },
  maintenance: { label: 'Maintenance', color: '#A78BFA', icon: 'wrench' },
};

// --- Fetch tank level by tank ID ---

let tankLevelsCache: TankLevelData[] | null = null;

export async function fetchTankLevels(): Promise<TankLevelData[]> {
  if (tankLevelsCache) return tankLevelsCache;
  const res = await apiFetch(`${API_BASE_URL}${API_ENDPOINTS.tank}/levels`);
  if (!res.ok) throw new Error(`Failed to fetch tank levels: ${res.status}`);
  const data = await res.json();
  tankLevelsCache = (Array.isArray(data) ? data : data.data ?? []) as TankLevelData[];
  return tankLevelsCache;
}

export async function fetchTankByOsmId(osmId: string): Promise<TankLevelData | null> {
  const tankId = osmToTankId(osmId);
  if (!tankId) return null;
  const levels = await fetchTankLevels();
  return levels.find((t) => t.tank === tankId) ?? null;
}

export function invalidateTankCache(): void {
  tankLevelsCache = null;
}

// --- Product color map ---
export const PRODUCT_COLORS: Record<string, string> = {
  Gasoline: '#F6AD55',
  Diesel: '#4D65FF',
  'Crude Oil': '#56CDE7',
  Crude: '#56CDE7',
  Ethanol: '#5CE5A0',
  LPG: '#5CE5A0',
};

// --- Formatting helpers ---

export function fmtVolume(v: number): string {
  if (v >= 1000) return `${(v / 1000).toFixed(1)}K`;
  return String(Math.round(v));
}

export function fmtPercent(v: number): string {
  return `${Math.round(v)}%`;
}

export function levelColor(level: number): string {
  if (level >= 80) return '#E53E3E'; // near full — warning
  if (level >= 60) return '#5CE5A0'; // healthy
  if (level >= 30) return '#F6AD55'; // medium
  return '#56CDE7'; // low
}
