import { API_BASE_URL, API_ENDPOINTS, apiFetch } from './config';

// --- Per-terminal OSM ID → Tank ID mappings ---
// Maps 3D scene mesh names (OSM building IDs) to tank database IDs.
// Generated by scanning GLB files for cylindrical meshes, sorted by size.

const SAVANNAH_TANKS: Record<string, string> = {
  '963060345': 'TK-301', '295318118': 'TK-302', '295318124': 'TK-201', '295318123': 'TK-202',
  '295318125': 'TK-203', '295318127': 'TK-101', '295318128': 'TK-102', '295318129': 'TK-103',
  '295318117': 'TK-401', '295318119': 'TK-402', '295318120': 'TK-503', '295318121': 'TK-501',
  '295318122': 'TK-504', '295318126': 'TK-502', '295318477': 'TK-511', '295318478': 'TK-519',
  '295318479': 'TK-505', '295318480': 'TK-520', '295318481': 'TK-521', '295318482': 'TK-522',
  '295318483': 'TK-523', '295318484': 'TK-512', '963018304': 'TK-526', '963018305': 'TK-527',
  '963018306': 'TK-528', '963018307': 'TK-529', '963018308': 'TK-530', '963018309': 'TK-531',
  '963018310': 'TK-532', '963018311': 'TK-533', '963018312': 'TK-534', '963018313': 'TK-506',
  '963018314': 'TK-507', '963018315': 'TK-508', '963018316': 'TK-509', '963060349': 'TK-524',
  '963060350': 'TK-525', '963060351': 'TK-536', '963060352': 'TK-537', '963060353': 'TK-538',
  '963060354': 'TK-539', '963060355': 'TK-540', '963060356': 'TK-541', '963060357': 'TK-542',
  '963060358': 'TK-543', '963060359': 'TK-544', '963060360': 'TK-545', '963060361': 'TK-546',
  '963060362': 'TK-547', '963060363': 'TK-548', '963060364': 'TK-513', '963060365': 'TK-514',
  '963060366': 'TK-515', '963060367': 'TK-516', '963060368': 'TK-517', '963060369': 'TK-510',
  '1286707729': 'TK-518', '1286707730': 'TK-535', '1286707731': 'TK-549',
};

const LA_TANKS: Record<string, string> = {
  '408512157': 'TK-101', '408512286': 'TK-102', '408512254': 'TK-103', '408512275': 'TK-104',
  '408512279': 'TK-105', '408512208': 'TK-201', '408512216': 'TK-202', '408512152': 'TK-203',
  '408512219': 'TK-204', '408512155': 'TK-205', '408512238': 'TK-301', '408512300': 'TK-302',
  '408512204': 'TK-303', '408512268': 'TK-304', '408512292': 'TK-305', '408512232': 'TK-306',
  '408512200': 'TK-307', '408512186': 'TK-401', '408512327': 'TK-402', '408512316': 'TK-403',
  '408512151': 'TK-404', '408512170': 'TK-405', '408512196': 'TK-406', '408512324': 'TK-407',
  '408512295': 'TK-501', '408512230': 'TK-502', '408512168': 'TK-503', '408512203': 'TK-504',
  '408512228': 'TK-505', '408512287': 'TK-506', '408512258': 'TK-507', '408512134': 'TK-508',
  '408512111': 'TK-509', '408512062': 'TK-510', '408511907': 'TK-511', '408511828': 'TK-512',
  '408511802': 'TK-513', '408511810': 'TK-514', '408511733': 'TK-515', '408512823': 'TK-516',
  '408512785': 'TK-517', '408512330': 'TK-518',
};

const TARRAGONA_TANKS: Record<string, string> = {
  '99699678': 'TK-101', '99699721': 'TK-102', '99699735': 'TK-103', '99699758': 'TK-104',
  '99699719': 'TK-105', '99699781': 'TK-106', '99699584': 'TK-201', '99699628': 'TK-202',
  '99699663': 'TK-203', '99699706': 'TK-204', '99699807': 'TK-205', '99699581': 'TK-206',
  '99699645': 'TK-301', '99699745': 'TK-302', '99699811': 'TK-303', '99699653': 'TK-304',
  '99699604': 'TK-305', '99699591': 'TK-306', '99699640': 'TK-401', '99699704': 'TK-402',
  '99699674': 'TK-403', '99699776': 'TK-404', '99699599': 'TK-405', '99699649': 'TK-406',
  '99699824': 'TK-501', '99699621': 'TK-502', '99699739': 'TK-503', '99699798': 'TK-504',
  '99699816': 'TK-505', '99699743': 'TK-506', '99699681': 'TK-601', '99699669': 'TK-602',
  '99699737': 'TK-603', '99699761': 'TK-604', '99699691': 'TK-605', '99699788': 'TK-606',
};

// Per-terminal mapping lookup
const TERMINAL_TANK_MAPS: Record<string, Record<string, string>> = {
  'savannah': SAVANNAH_TANKS,
  'los-angeles': LA_TANKS,
  'tarragona': TARRAGONA_TANKS,
};

function getActiveMap(): Record<string, string> {
  if (typeof window !== 'undefined') {
    const tid = localStorage.getItem('vopak_active_terminal') || 'savannah';
    return TERMINAL_TANK_MAPS[tid] ?? SAVANNAH_TANKS;
  }
  return SAVANNAH_TANKS;
}

export function osmToTankId(osmId: string): string | null {
  return getActiveMap()[osmId] ?? null;
}

export function isMappedTank(osmId: string): boolean {
  return osmId in getActiveMap();
}

// --- Tank data types ---

export type TankStatus =
  | 'in_service'
  | 'receiving'
  | 'discharging'
  | 'idle'
  | 'heating'
  | 'warning'
  | 'critical'
  | 'maintenance';

export interface TankLevelData {
  id: number;
  tank: string;
  product: string;
  level: number;
  volume: number;
  capacity: number;
  color: string;
  status: TankStatus;
}

// Status display config for UI and 3D visualization
export const TANK_STATUS_CONFIG: Record<TankStatus, { label: string; color: string; icon: string }> = {
  in_service:  { label: 'In Service',  color: '#5CE5A0', icon: 'check-circle' },
  receiving:   { label: 'Receiving',   color: '#56CDE7', icon: 'arrow-down' },
  discharging: { label: 'Discharging', color: '#4D65FF', icon: 'arrow-up' },
  idle:        { label: 'Idle',        color: '#94A3B8', icon: 'pause-circle' },
  heating:     { label: 'Heating',     color: '#F6AD55', icon: 'flame' },
  warning:     { label: 'Warning',     color: '#ECC94B', icon: 'alert-triangle' },
  critical:    { label: 'Critical',    color: '#E53E3E', icon: 'alert-octagon' },
  maintenance: { label: 'Maintenance', color: '#A78BFA', icon: 'wrench' },
};

// --- Fetch tank level by tank ID ---

let tankLevelsCache: TankLevelData[] | null = null;

export async function fetchTankLevels(): Promise<TankLevelData[]> {
  if (tankLevelsCache) return tankLevelsCache;
  const res = await apiFetch(`${API_BASE_URL}${API_ENDPOINTS.tank}/levels`);
  if (!res.ok) throw new Error(`Failed to fetch tank levels: ${res.status}`);
  const data = await res.json();
  tankLevelsCache = (Array.isArray(data) ? data : data.data ?? []) as TankLevelData[];
  return tankLevelsCache;
}

export async function fetchTankByOsmId(osmId: string): Promise<TankLevelData | null> {
  const tankId = osmToTankId(osmId);
  if (!tankId) return null;
  const levels = await fetchTankLevels();
  return levels.find((t) => t.tank === tankId) ?? null;
}

export function invalidateTankCache(): void {
  tankLevelsCache = null;
}

// --- Product color map ---
export const PRODUCT_COLORS: Record<string, string> = {
  Gasoline: '#F6AD55',
  Diesel: '#4D65FF',
  'Crude Oil': '#56CDE7',
  Crude: '#56CDE7',
  Ethanol: '#5CE5A0',
  LPG: '#5CE5A0',
};

// --- Formatting helpers ---

export function fmtVolume(v: number): string {
  if (v >= 1000) return `${(v / 1000).toFixed(1)}K`;
  return String(Math.round(v));
}

export function fmtPercent(v: number): string {
  return `${Math.round(v)}%`;
}

export function levelColor(level: number): string {
  if (level >= 80) return '#E53E3E'; // near full — warning
  if (level >= 60) return '#5CE5A0'; // healthy
  if (level >= 30) return '#F6AD55'; // medium
  return '#56CDE7'; // low
}
